### ISSUE TITLE
Error is thrown while discarding/checkout the file

### ISSUE THREAD

**Issue by aankittcoolest** [jreybert/vimagit#118]
Here are the details of the error displayed.

<pre>
Error detected while processing function magit#stage_hunk[32]..magit#stage_block[29]..magit#git#git_unapply:
line   18:
E605: Exception not caught: unapply error
Error detected while processing function magit#stage_hunk[32]..magit#stage_block:
line   29:
E171: Missing :endif
</pre>

Any details as to why is this thrown?

**Comment by jreybert** [comment]
I need more context, I can't reproduce your issue.
- What action are you doing (stage, unstage)
- Could you provide a screenshot or the hunk part (with the hunk header) you tried to unstage.
- Did it happened since `master` branch upgrade?
- Just in case: [n]vim version, git version, OS (Linux,Mac,Windows)

**Comment by aankittcoolest** [comment]
I committed he code in the normal way then!
Will be reporting it again (this time with more details) if encountered again.
Closing the issue for now.
