### ISSUE TITLE
Pressing 0 (zero) in commit section adds new line

### ISSUE THREAD

**Issue by argshook** [jreybert/vimagit#124]
In commit section, whilst editing commit message, hitting `0` in normal mode calls `magit#update_diff('0')`. I expect `0` to work as in normal mode - move cursor to beginning of line. Instead, it adds new line under `Commit message` heading and moves cursor there.

ideally, none of the diff mappings (and possibly others) should work whilst in commit section.

didn't investigate this at all, just reporting.

**Comment by jreybert** [comment]
`0` is mapped to reset the hunk context size to its default. It also starts a refresh of the magit buffer, with the new hunk context size.

Real problem here (as you pointed it out) is that vimagit mappings are not section aware. I'm quite reluctant to distinguish mapping effect on current section, I already thought about that when I tried #101. It is not that difficult, but I fear it would be error prone.

Anyway, which mappings should work in commit sections?
* `CC`
* `CA`
* `R` ?
* `<C-n>` `<C-p>`
* `?`
* Any other thought?

**Comment by argshook** [comment]
maybe there is a way to configure and disable `0` entirely? `-` and `+` is enough for me.

as per mappings, for me it's okay to have whatever mappings as long as they don't collide with vim defaults. or at least as little as possible

**Comment by jreybert** [comment]
At least, you can remap `0` to something else, setting `g:magit_diff_reset` to whatever you want.

**Comment by argshook** [comment]
`nunmap` works, so i'll probably just stick this in my `vimrc`:

```
autocmd User VimagitBufferInit nunmap <silent> <buffer> 0
```
