### ISSUE TITLE
support buffer-based git repo?

### ISSUE THREAD

**Issue by goweol** [jreybert/vimagit#44]
When I open a file in another git repo, ':Magit' shows status for current repo (where I started vim).
Fugitive (Gstatus) shows status for another repo (for current buffer).

I hope magit support buffer-based git repo (optional?).

BTW, ':cd %:p:h' didnot help.  :Magit shows old repo status, though I changed to another repo.  I expected magit shows status for VIM's current directory.
It may related to submodule feature (I use many submodules).

<blockquote>
$ git rev-parse --show-toplevel<br>
/data/test/lib<br>
<br>
$ git rev-parse --git-dir<br>
/data/test/.git/modules/lib
</blockquote>

If I start VIM in that another repo, :Magit shows status for that repo.

**Comment by jreybert** [comment]
No, magit does not handle it for the moment.

See #29 and #34

**Comment by haifengkao** [comment]
#29 has a easy fix for it

**Comment by jreybert** [comment]
The fix is easy, but I can't predict what are the side effects. vimagit use a lot of buffer variables to cache some stuff. But I have no time at this moment to perform a deep code review to check that nothing is broken, and the actual test suite does not cover this case.

Like I said in #29, I prefer a solution where I open a new buffer for each git repository, but it asks some time to develop.

Actually, you can try the #29 pull request. It may even work! But as long as I don't add a test case for this, it won't be merged in vimagit.

**Comment by jreybert** [comment]
I believe that this feature is now added in branch dev/multiple_repo.

I'll wait for your feedback before merging it in next.

**Comment by goweol** [comment]
dev/multiple_repo works fine for me

Thanks
