### ISSUE TITLE
Option let g:magit_show_help = 0 doesn't seem to work

### ISSUE THREAD

**Issue by wikimatze** [jreybert/vimagit#88]
Pressing `h` gives me the same output as well as setting the option to 1. I thought pressing `h` will do nothing anymore and the line "Press h to display help" will not be shown or does the option something other?

Thanks for the fugitive replacement.

Cheers,
Matthias

**Comment by jreybert** [comment]
Some misunderstanding I think:
- `g:magit_show_help` shows the help by default when opening magit buffer
- in next and master branches, you must now use '?' instead of 'h' to toggle help showing

Anyway, I am not sure what you're trying to achieve.

PS: vimagit does not aim to replace fugitive ;) I still use both (I don't intend to replace Gblame, Gdiff, Ggrep or Gedit!!!)

**Comment by wikimatze** [comment]
Thanks for the explanation - didn't notice that help is there when opening a new window :smile: - so this option makes totally sense now.

I forget about `:Gblame` (not using it for OS work that much) but yeah, definitely an argument to stay with fugitive.

Thanks for clarification!

Cheers,

Matthias
